### ISSUE TITLE
Does not compile on Raspberry Pi OS 64 Bit

### ISSUE THREAD

**Issue by cHemingway** [roboportal/bot_box#14]
Using go 19.4 arm64 on Raspberry Pi OS 64bit 2023-05-03
```
$ uname -smor
Linux 6.1.21-v8+ aarch64 GNU/Linux
$go version
go version go1.19.4 linux/arm64
```

When compiling, I get this unrecognized instruction error:
```
$ CGO_LDFLAGS="-latomic" go build -tags=arm
[... snipped ...]
# runtime/internal/syscall
/usr/local/go/src/runtime/internal/syscall/defs_linux_arm64.go:7:7: SYS_FCNTL redeclared in this block
        /usr/local/go/src/runtime/internal/syscall/defs_linux_arm.go:7:7: other declaration of SYS_FCNTL
# math
/usr/local/go/src/math/sqrt_arm.s:13: unrecognized instruction "SQRTD"
asm: assembly of /usr/local/go/src/math/sqrt_arm.s failed
```

**Comment by malykhin** [comment]
Thanks for reporting this. Last time I tried compiling it for 64 bit Raspbian it wasn’t working due to camera-related dependencies. There is still a handful of pancakes which aren’t compatible with 64 bit. Is there a specific reason you wanna run it on this is version ?

**Comment by cHemingway** [comment]
No particular reason, its just what I already was running. I will try the 32 bit and report back.
Might I suggest the README is updated to specify it only works on 32 bit?

**Comment by cHemingway** [comment]
Running a clean install of the latest Raspberry Pi OS 32 bit, it compiles for me fine, so I can confirm this issue is 64 bit specific.

**Comment by cHemingway** [comment]
Related, it appears I can't run go-delve on 32 bit arm, which I was going to use for debugging as thats what the VSCode extension uses.  See https://github.com/go-delve/delve/issues/1933

**Comment by malykhin** [comment]
Hi @cHemingway,

I successfully compiled bot_box on 64-bit Raspbian using go1.21.1.linux-arm64. The correct command for arm64 is: `CGO_LDFLAGS="-latomic" go build -tags=arm64`.

Thanks for reporting this. I'll update the README.md to include this information.
