### ISSUE TITLE
Audio Not Transmitting from Raspberry Pi to Browser in Webrtc Bot

### ISSUE THREAD

**Issue by kadharsh** [roboportal/bot_box#16]
Thank you for this great project.

I've been working on setting up a Webrtc bot following the provided instructions. The project works wonderfully overall. However, I've encountered an issue with audio transmission from the Raspberry Pi to the browser. 
I can successfully talk on my PC, and the Raspberry Pi is playing the sound. However, the audio is not transmitted from the Raspberry Pi to the browser. The camera and controls work as expected.

I've tested the audio recording on the Raspberry Pi using the `arecord` command, and it works fine. I can record and playback without any issues. I have also tried the `gen2brain/malgo` example code `capture` which was also working fine.

**.env file:**
```                                                                                 
srv_url = "wss://api.roboportal.io:8001"

public_key = "xxxxxx-xxxxxxxxx-xxxxxxxxx-xxxxxx"
secret_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

stun_urls = "stun:stun.l.google.com:19302"
video_codec_bit_rate = 1000000
frame_format = "RGBA"
video_width = 800
video_frame_rate = 30

audio_input_enabled = true
audio_output_enabled = true

output_mode = console
port_name = "/dev/serial/by-id/..."
baud_rate = 115200

bot_box_ipc_port = 5555
robot_ipc_port = 5556
robot_ipc_host = 127.0.0.1

camera_multiplexor_i2c_bus = 1

debug = true
```
I am using a generic USB audio card for capturing and playing the audio, which I have set as the default card in `/usr/share/alsa/alsa.conf`

**My setup:**
* Raspberry Pi 4B
* OS: 32bit Raspbian GNU/Linux 12 (bookworm)
* go version 1.21.4

Let me know if you need more details. Appreciate your help!

**Comment by malykhin** [comment]
Thanks for reporting this, @kadharsh. 

We'll need a few days to ensure there is no regression and that the software is functioning correctly. We'll get back to you after confirming.

**Comment by kadharsh** [comment]
Hi @malykhin 

Thanks a ton for the quick response!  Take your time, and I appreciate your efforts. Feel free to reach out if you need any more info or testing on my end.

**Comment by kadharsh** [comment]
Hi @malykhin 

Thanks a ton for the quick response!  Take your time, and I appreciate your efforts. Feel free to reach out if you need any more info or testing on my end.

**Comment by malykhin** [comment]
Hi @kadharsh 
I've checked the microphone and it works well.
[The mic that I tested](https://www.amazon.ca/dp/B01KLRBHGM) (it's just the one that I was able to get quickly).
Steps I used to set it up:
1.  Getting the record device details:
<img width="905" alt="Screenshot 2023-11-17 at 7 15 02 PM" src="https://github.com/roboportal/bot_box/assets/15819745/7c1171aa-5f3a-419d-b2b4-8d1a7ba0a626">
2. Configuration: 
<img width="900" alt="Screenshot 2023-11-17 at 7 15 23 PM" src="https://github.com/roboportal/bot_box/assets/15819745/87f27ccd-7775-47dc-8f43-239f69ac4394">
3. Setting the gain:
<img width="910" alt="Screenshot 2023-11-17 at 7 13 35 PM" src="https://github.com/roboportal/bot_box/assets/15819745/d8e63d4c-d0d3-4bdb-9c2f-e51bb1af13aa">

**Comment by kadharsh** [comment]
Hi @malykhin 

I've reviewed my setup, and I seem to be following similar steps, but unfortunately, the audio is not coming through on the other side. Am I missing something?
Here is the configuration I'm using:
1 .env file is the same 
2. record device details and OS:
![Screenshot from 2023-11-20 11-22-38](https://github.com/roboportal/bot_box/assets/58363243/b76dbb33-2789-42eb-8717-9b7f81d7da2d)
3. Alsa Configuration
![Screenshot from 2023-11-20 11-54-36](https://github.com/roboportal/bot_box/assets/58363243/141490af-799c-4528-a7e7-8b8aa46b4480)
4. alsamixer
![Screenshot from 2023-11-20 11-22-04](https://github.com/roboportal/bot_box/assets/58363243/bb634fc2-7913-401a-ac0b-98802db5b3e2)
5. pion debug log
![Screenshot from 2023-11-20 11-35-21](https://github.com/roboportal/bot_box/assets/58363243/3afbc1d1-a1d9-43e0-8dbb-675b70e8a4f3)

But no audio output from the browser, the speaker option in the video player is blacked out.
![Screenshot from 2023-11-20 11-38-32](https://github.com/roboportal/bot_box/assets/58363243/a441c57d-4348-4db3-8b26-157e6cf40f03)

I've tested the microphone by recording a small audio file using this command `arecord -f S16_LE -r 44100 audio_file.wav`, and that's working.

**Comment by malykhin** [comment]
The setup looks good to me.
Could you please try using headphones instead of speakers on your computer? I've noticed that my browser disables WebRTC audio if feedback occurs. 
Could you please share the link to the audio device you're using? I can test it on my end.

**Comment by kadharsh** [comment]
I tried using headphones with my PC, but unfortunately, the issue persists. The USB device I am using is [Plextone GS3](https://www.shopz.com.bd/product/plextone-gs3-virtual-7-1-channel-usb-sound-card-driver/). Additionally, I attempted to use the microphone of the USB webcam **Logitech C270**, and the problem remained the same.

**Comment by kadharsh** [comment]
I've identified the issue – it was related to ALSA. After installing `pulseaudio`, the `miniaudio` started selecting it as the backend, resolving the problem. Now, the audio works in both directions. Additionally, I encountered distorted audio, and I solved it using this patch: https://github.com/pion/mediadevices/issues/500
Thank you @malykhin for your time and support; I appreciate it.
