### ISSUE TITLE
How do I config the env file and main.go file for an IP camera

### ISSUE THREAD

**Issue by manbirrrr19** [roboportal/bot_box#17]
this is my .env file:
srv_url = "wss://api.roboportal.io:8001"

public_key = "<my public key>"
secret_key = "<my private key>"

stun_urls = "stun:stun.l.google.com:19302"
video_codec_bit_rate = 1000000
frame_format = "RGBA"
video_width = 640
video_frame_rate = 30

audio_input_enabled = false
audio_output_enabled = false

output_mode = ipc

video_source_ip = "<ip>"
video_source_port = 8080

bot_box_ipc_port = 5555
robot_ipc_port = 5556
robot_ipc_host = 127.0.0.1

camera_multiplexor_i2c_bus = 1

debug = false

idk how to config my main.go file for these settings because there are things like baud rate and not video source ip inside

**Comment by malykhin** [comment]
Hi @manbirrrr19

This project doesn't support IP cameras as a video source. Do you have a particular use case for a robotic application that requires the usage of an IP camera?

**Comment by manbirrrr19** [comment]
Thanks for replying. What other cameras can I use? I want something that can stream vids in real time. Also is it possible to use this project without a camera at all(just controls like movement)?

**Comment by malykhin** [comment]
We tested raspberry cameras and web cameras like Logitech c270.
 The project couldn’t be run without a camera. The whole idea is to use it to control something in real time over the internet. I don’t think it’s feasible without video stream. If you want to build a remote control for something in the local network, you don’t need all that overhead that we offer.
